### ISSUE TITLE
你好，请问能否详细讲一下使用流程？

### ISSUE THREAD

**Issue by kjsolo** [r0ysue/r0capture#1]
我是Python新手，不太明白frida的机制
运行项目时出现frida.ServerNotRunningError: unable to connect to remote frida-server: closed
我想应该是我没有开启服务之类的，能否详细说一下这个抓包的流程？

**Comment by r0ysue** [comment]
你要先把frida的环境给准备好呀~
https://frida.re/docs/android/

**Comment by kjsolo** [comment]
Frida是需要Root设备吗
