### ISSUE TITLE
浏览器抓包

### ISSUE THREAD

**Issue by dadaewqq** [r0ysue/r0capture#14]
# 问候
你好呀！
# 现象
刚开始抓的一般app没发现问题。
不过后来试着抓浏览器的包，试了好几个浏览器都发现没有抓下东西
# 疑惑
个人猜想不是因为包名选的是浏览器，但是浏览网页时的流量是通过webview的，所以抓不到？

**Comment by r0ysue** [comment]
![捕获](https://user-images.githubusercontent.com/23090578/101112240-d32cac00-3617-11eb-825c-4e3608ea0f59.PNG)
从nethogs确定的进程来看，收发包一定在这个进程中。
![捕获2](https://user-images.githubusercontent.com/23090578/101112349-0c651c00-3618-11eb-8abb-ee717dec1013.PNG)
从对该进程trace Socket的结果来看，确实走的是conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read和ConscryptFileDescriptorSocket$SSLOutputStream.write，理论上是可以抓到的才对。。。今天没时间分析了，回头再仔细分析下（咕咕咕

**Comment by r0ysue** [comment]
有兴趣加我vx，我们一起研究。

**Comment by r0ysue** [comment]
用DDMS来trace试了下，发现Java层是没有任何收发包的接口的。
猜想chromium是一套完整的跨平台C++写的内核，因为它横跨全PC/移动终端平台，所以Java层啥都没有，连SSL库都用的自己写的。所以得单独逆它才行，它完全没有走通用API。
