### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by ybm911** [r0ysue/r0capture#18]
你好👋作者大大，首先我拿到这个项目。我以为是可以局域网arp欺骗然后截获android设备的所有ssl流量。可是我看到你的参数-U 后面连接的是com.qiyi.video，而且执行中没有输入任何ip地址，我不太懂这是什么意思。-U参数是connect to USB device，我也在网上搜了一下，目前没有次项目的教程。请问能请教一下吗？ @r0ysue

**Comment by r0ysue** [comment]
需要Frida环境噢 ~
https://frida.re/docs/android/
https://github.com/r0ysue/AndroidSecurityStudy/blob/master/FRIDA/A01/README.md
