### ISSUE TITLE
does not working on Genymotion

### ISSUE THREAD

**Issue by gaplan** [r0ysue/r0capture#19]
hi there 
does not working on Genymotion
facebook , or twitter or instagram

**Comment by gaplan** [comment]
i think Doesn't work on apps with ssl pinning @r0ysue what do u think ?

**Comment by r0ysue** [comment]
please paste the error message 
or 
TRY IT ON A  REAL PHONE ~

**Comment by gaplan** [comment]
There is no error message there.

for exp if i try to pinterest app  i can see variables.

Pinterest doesn't use SSL pinning.

but if i try instagram, facebook, youtube etc.
does not working. without error.

If I ask, would you try one of these apps?



<img width="1259" alt="Screen Shot 2020-12-11 at 01 49 20" src="https://user-images.githubusercontent.com/2036941/101839303-2ee4c100-3b53-11eb-993a-f79d37bbbd7c.png">

**Comment by gaplan** [comment]
@r0ysue ?

**Comment by daisixuan** [comment]
Maybe the application you listed doesn't use the Android System API @gaplan
