### ISSUE TITLE
经测试，flutter 开发的app ，抓不到包，android6.0

### ISSUE THREAD

**Issue by mickeystone** [r0ysue/r0capture#2]
```
{'columnNumber': 1,
 'description': "Error: java.lang.ClassNotFoundException: Didn't find class "
                '"java.net.SocketOutputStream" on path: DexPathList[[zip file '
                '"/data/app/com.test.vc-2/base.apk"],nativeLibraryDirectories=[/data/app/com.test.vc-2/lib/arm, '
                '/data/app/com.test.vc-2/base.apk!/lib/armeabi-v7a, '
                '/vendor/lib, /system/lib]]',
 'fileName': 'frida/node_modules/frida-java-bridge/lib/env.js',
 'lineNumber': 124,
 'stack': "Error: java.lang.ClassNotFoundException: Didn't find class "
          '"java.net.SocketOutputStream" on path: DexPathList[[zip file '
          '"/data/app/com.test.vc-2/base.apk"],nativeLibraryDirectories=[/data/app/com.test.vc-2/lib/arm, '
          '/data/app/com.test.vc-2/base.apk!/lib/armeabi-v7a, /vendor/lib, '
          '/system/lib]]\n'
          '    at <anonymous> '
          '(frida/node_modules/frida-java-bridge/lib/env.js:124)\n'
          '    at <anonymous> '
          '(frida/node_modules/frida-java-bridge/lib/class-factory.js:443)\n'
          '    at value '
          '(frida/node_modules/frida-java-bridge/lib/class-factory.js:812)\n'
          '    at _make '
          '(frida/node_modules/frida-java-bridge/lib/class-factory.js:112)\n'
          '    at use '
          '(frida/node_modules/frida-java-bridge/lib/class-factory.js:63)\n'
          '    at use (frida/node_modules/frida-java-bridge/index.js:245)\n'
          '    at <anonymous> (/script1.js:190)\n'
          '    at <anonymous> '
          '(frida/node_modules/frida-java-bridge/lib/vm.js:12)\n'
          '    at _performPendingVmOps '
          '(frida/node_modules/frida-java-bridge/index.js:237)\n'
          '    at <anonymous> '
          '(frida/node_modules/frida-java-bridge/index.js:212)\n'
          '    at <anonymous> '
          '(frida/node_modules/frida-java-bridge/lib/vm.js:12)\n'
          '    at _performPendingVmOpsWhenReady '
          '(frida/node_modules/frida-java-bridge/index.js:231)\n'
          '    at perform (frida/node_modules/frida-java-bridge/index.js:191)\n'
          '    at <eval> (/script1.js:222)',
 'type': 'error'}
```

**Comment by mickeystone** [comment]
`{'columnNumber': 1,
 'description': "Error: java.lang.ClassNotFoundException: Didn't find class "
                '"java.net.SocketOutputStream" on path: DexPathList[[zip file '
                '"/data/app/com.test.vc-2/base.apk"],nativeLibraryDirectories=[/data/app/com.test.vc-2/lib/arm, '
                '/data/app/com.test.vc-2/base.apk!/lib/armeabi-v7a, '
                '/vendor/lib, /system/lib]]',
 'fileName': 'frida/node_modules/frida-java-bridge/lib/env.js',
 'lineNumber': 124,
 'stack': "Error: java.lang.ClassNotFoundException: Didn't find class "
          '"java.net.SocketOutputStream" on path: DexPathList[[zip file '
          '"/data/app/com.test.vc-2/base.apk"],nativeLibraryDirectories=[/data/app/com.test.vc-2/lib/arm, '
          '/data/app/com.test.vc-2/base.apk!/lib/armeabi-v7a, /vendor/lib, '
          '/system/lib]]\n'
          '    at <anonymous> '
          '(frida/node_modules/frida-java-bridge/lib/env.js:124)\n'
          '    at <anonymous> '
          '(frida/node_modules/frida-java-bridge/lib/class-factory.js:443)\n'
          '    at value '
          '(frida/node_modules/frida-java-bridge/lib/class-factory.js:812)\n'
          '    at _make '
          '(frida/node_modules/frida-java-bridge/lib/class-factory.js:112)\n'
          '    at use '
          '(frida/node_modules/frida-java-bridge/lib/class-factory.js:63)\n'
          '    at use (frida/node_modules/frida-java-bridge/index.js:245)\n'
          '    at <anonymous> (/script1.js:190)\n'
          '    at <anonymous> '
          '(frida/node_modules/frida-java-bridge/lib/vm.js:12)\n'
          '    at _performPendingVmOps '
          '(frida/node_modules/frida-java-bridge/index.js:237)\n'
          '    at <anonymous> '
          '(frida/node_modules/frida-java-bridge/index.js:212)\n'
          '    at <anonymous> '
          '(frida/node_modules/frida-java-bridge/lib/vm.js:12)\n'
          '    at _performPendingVmOpsWhenReady '
          '(frida/node_modules/frida-java-bridge/index.js:231)\n'
          '    at perform (frida/node_modules/frida-java-bridge/index.js:191)\n'
          '    at <eval> (/script1.js:222)',
 'type': 'error'}`

**Comment by r0ysue** [comment]
基于Java的虚拟机，flutter走的已经不是java的虚拟机了，确实是无效的。
后续我写到说明限制里去。

**Comment by maryammsd** [comment]
I face the same issue. What is the solution to it?

**Comment by owen800q** [comment]
> I face the same issue. What is the solution to it?

Currently, it sees to be no proper way to bypass flutter ssl pinning...
