### ISSUE TITLE
小米运动APP 报错

### ISSUE THREAD

**Issue by lxwcv** [r0ysue/r0capture#23]
运行抓包脚本报错

**Comment by r0ysue** [comment]
报啥错倒是贴上来康康呢~

**Comment by lxwcv** [comment]
首先进程显示两个
6753&nbsp; com.xiaomi.hm.health
6799&nbsp; com.xiaomi.hm.health



运行:r0capture.py -U com.xiaomi.hm.health -p iqiyi.pcap
报错如下:
attach
Traceback (most recent call last):
&nbsp; File "D:\迅雷下载\r0capture-main\r0capture.py", line 346, in <module&gt;
&nbsp; &nbsp; ssl_log(int(parsed.process) if parsed.process.isdigit() else parsed.process, parsed.pcap, parsed.verbose, isUsb=parsed.isUsb, isSpawn=parsed.isSpawn, ssllib=parsed.ssl, wait=parsed.wait)
&nbsp; File "D:\迅雷下载\r0capture-main\r0capture.py", line 256, in ssl_log
&nbsp; &nbsp; session = device.attach(process)
&nbsp; File "C:\Users\13949\AppData\Local\Programs\Python\Python39\lib\site-packages\frida\core.py", line 26, in wrapper
&nbsp; &nbsp; return f(*args, **kwargs)
&nbsp; File "C:\Users\13949\AppData\Local\Programs\Python\Python39\lib\site-packages\frida\core.py", line 156, in attach
&nbsp; &nbsp; return Session(self._impl.attach(self._pid_of(target)))
&nbsp; File "C:\Users\13949\AppData\Local\Programs\Python\Python39\lib\site-packages\frida\core.py", line 180, in _pid_of
&nbsp; &nbsp; return self.get_process(target).pid
&nbsp; File "C:\Users\13949\AppData\Local\Programs\Python\Python39\lib\site-packages\frida\core.py", line 26, in wrapper
&nbsp; &nbsp; return f(*args, **kwargs)
&nbsp; File "C:\Users\13949\AppData\Local\Programs\Python\Python39\lib\site-packages\frida\core.py", line 110, in get_process
&nbsp; &nbsp; raise _frida.ProcessNotFoundError("ambiguous name; it matches: %s" % ", ".join(["%s (pid: %d)" % (process.name, process.pid) for process in matching]))
frida.ProcessNotFoundError: ambiguous name; it matches: com.xiaomi.hm.health (pid: 6753), com.xiaomi.hm.health (pid: 6799)



输入:r0capture.py -U 6753 -p iqiyi.pcap
报错如下:
attach
Traceback (most recent call last):
&nbsp; File "D:\迅雷下载\r0capture-main\r0capture.py", line 346, in <module&gt;
&nbsp; &nbsp; ssl_log(int(parsed.process) if parsed.process.isdigit() else parsed.process, parsed.pcap, parsed.verbose, isUsb=parsed.isUsb, isSpawn=parsed.isSpawn, ssllib=parsed.ssl, wait=parsed.wait)
&nbsp; File "D:\迅雷下载\r0capture-main\r0capture.py", line 256, in ssl_log
&nbsp; &nbsp; session = device.attach(process)
&nbsp; File "C:\Users\13949\AppData\Local\Programs\Python\Python39\lib\site-packages\frida\core.py", line 26, in wrapper
&nbsp; &nbsp; return f(*args, **kwargs)
&nbsp; File "C:\Users\13949\AppData\Local\Programs\Python\Python39\lib\site-packages\frida\core.py", line 156, in attach
&nbsp; &nbsp; return Session(self._impl.attach(self._pid_of(target)))
frida.PermissionDeniedError: unable to access process with pid 6753 due to system restrictions; try `sudo sysctl kernel.yama.ptrace_scope=0`, or run Frida as root



输入另一个PID也是同样的报错&nbsp; 安装环境没有问题 其他APP抓包正常&nbsp;&nbsp;
感谢回复&nbsp; 么么哒
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "r0ysue/r0capture"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月17日(星期四) 上午10:47
收件人:&nbsp;"r0ysue/r0capture"<r0capture@noreply.github.com&gt;;
抄送:&nbsp;"落雪无尘"<1394926200@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [r0ysue/r0capture] 小米运动APP 报错 (#23)





 
报啥错倒是贴上来康康呢~

**Comment by r0ysue** [comment]
这是典型的双进程保护。
![图片](https://user-images.githubusercontent.com/23090578/102438874-1cd5b780-4058-11eb-9a34-c3665db38992.png)
是可以解决的
方法见我的星球：https://t.zsxq.com/QBaia62
