### ISSUE TITLE
两种用法对真机上的APP抓包时总是抓不到任何包

### ISSUE THREAD

**Issue by YIRUIJIE** [r0ysue/r0capture#25]
我尝试了好几个APP最终都是没有成功抓到包。(google真机实验：酷安9.6.2版、Instagram165版等其他都没有成功)

**Spawn 模式运行：被抓包的APP直接闪屏退出，随后出现下面的错误，接着又重新自动启动。**

Press Ctrl+C to stop logging.
{'columnNumber': 1,
 'description': "Error: java.lang.ClassNotFoundException: Didn't find class "
                '"java.net.SocketOutputStream" on path: DexPathList[[zip file '
                '"/data/app/com.instagram.android-1/base.apk"],nativeLibraryDirectories=[/data/app/com.instagram.android-1/lib/x86, '
                '/data/app/com.instagram.android-1/base.apk!/lib/x86, '
                '/vendor/lib, /system/lib]]',
 'fileName': 'frida/node_modules/frida-java-bridge/lib/env.js',
 'lineNumber': 124,
 'stack': "Error: java.lang.ClassNotFoundException: Didn't find class "
          '"java.net.SocketOutputStream" on path: DexPathList[[zip file '
          '"/data/app/com.instagram.android-1/base.apk"],nativeLibraryDirectories=[/data/app/com.instagram.android-1/lib/x86, '
          '/data/app/com.instagram.android-1/base.apk!/lib/x86, /vendor/lib, '
          '/system/lib]]\n'
          '    at <anonymous> '
          '(frida/node_modules/frida-java-bridge/lib/env.js:124)\n'
          '    at <anonymous> '
          '(frida/node_modules/frida-java-bridge/lib/class-factory.js:443)\n'
          '    at value '
          '(frida/node_modules/frida-java-bridge/lib/class-factory.js:812)\n'
          '    at _make '
          '(frida/node_modules/frida-java-bridge/lib/class-factory.js:112)\n'
          '    at use '
          '(frida/node_modules/frida-java-bridge/lib/class-factory.js:63)\n'
          '    at use (frida/node_modules/frida-java-bridge/index.js:245)\n'
          '    at <anonymous> (/script1.js:192)\n'
          '    at <anonymous> '
          '(frida/node_modules/frida-java-bridge/lib/vm.js:12)\n'
          '    at _performPendingVmOps '
          '(frida/node_modules/frida-java-bridge/index.js:237)\n'
          '    at <anonymous> '
          '(frida/node_modules/frida-java-bridge/index.js:229)\n'
          '    at apply (native)\n'
          '    at ne '
          '(frida/node_modules/frida-java-bridge/lib/class-factory.js:613)\n'
          '    at <anonymous> '
          '(frida/node_modules/frida-java-bridge/lib/class-factory.js:592)',
 'type': 'error'}

**Attach 模式运行：也是会出现错误，并会在r0capture.py同级目录下生成空的 .pacp文件。错误如下：**

attach
{'columnNumber': 1,
 'description': "Error: java.lang.ClassNotFoundException: Didn't find class "
                '"java.net.SocketOutputStream" on path: DexPathList[[zip file '
                '"/data/app/com.instagram.android-1/base.apk"],nativeLibraryDirectories=[/data/app/com.instagram.android-1/lib/x86, '
                '/data/app/com.instagram.android-1/base.apk!/lib/x86, '
                '/vendor/lib, /system/lib]]',
 'fileName': 'frida/node_modules/frida-java-bridge/lib/env.js',
 'lineNumber': 124,
 'stack': "Error: java.lang.ClassNotFoundException: Didn't find class "
          '"java.net.SocketOutputStream" on path: DexPathList[[zip file '
          '"/data/app/com.instagram.android-1/base.apk"],nativeLibraryDirectories=[/data/app/com.instagram.android-1/lib/x86, '
          '/data/app/com.instagram.android-1/base.apk!/lib/x86, /vendor/lib, '
          '/system/lib]]\n'
          '    at <anonymous> '
          '(frida/node_modules/frida-java-bridge/lib/env.js:124)\n'
          '    at <anonymous> '
          '(frida/node_modules/frida-java-bridge/lib/class-factory.js:443)\n'
          '    at value '
          '(frida/node_modules/frida-java-bridge/lib/class-factory.js:812)\n'
          '    at _make '
          '(frida/node_modules/frida-java-bridge/lib/class-factory.js:112)\n'
          '    at use '
          '(frida/node_modules/frida-java-bridge/lib/class-factory.js:63)\n'
          '    at use (frida/node_modules/frida-java-bridge/index.js:245)\n'
          '    at <anonymous> (/script1.js:192)\n'
          '    at <anonymous> '
          '(frida/node_modules/frida-java-bridge/lib/vm.js:12)\n'
          '    at _performPendingVmOps '
          '(frida/node_modules/frida-java-bridge/index.js:237)\n'
          '    at <anonymous> '
          '(frida/node_modules/frida-java-bridge/index.js:212)\n'
          '    at <anonymous> '
          '(frida/node_modules/frida-java-bridge/lib/vm.js:12)\n'
          '    at _performPendingVmOpsWhenReady '
          '(frida/node_modules/frida-java-bridge/index.js:231)\n'
          '    at perform (frida/node_modules/frida-java-bridge/index.js:191)\n'
          '    at <eval> (/script1.js:224)',
 'type': 'error'}

我相信这个应该不只有我自己遇到，希望之前有遇到并解决了这个问题的朋友们可以交流一下，谢谢！

**Comment by r0ysue** [comment]
写了安卓7、8、9、10 .
