### ISSUE TITLE
怎么连接模拟器

### ISSUE THREAD

**Issue by codeforme123** [r0ysue/r0capture#26]
是否可以增加连接模拟器的功能？手机有时候不方便

**Comment by r0ysue** [comment]
不支持模拟器噢 ~

**Comment by YIRUIJIE** [comment]
雷电模拟器的最新版本 Android 7.1.2系统我试验过了，是可以支持使用的！

**Comment by T-Jinhao** [comment]
> 雷电模拟器的最新版本 Android 7.1.2系统我试验过了，是可以支持使用的！

你好，请问如何操作呢？有教程吗？

**Comment by YIRUIJIE** [comment]
使用看这篇文章：https://www.52pojie.cn/forum.php?mod=viewthread&amp;tid=1349195




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "r0ysue/r0capture"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月22日(星期五) 晚上6:14
收件人:&nbsp;"r0ysue/r0capture"<r0capture@noreply.github.com&gt;;
抄送:&nbsp;"杰孑"<923494352@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [r0ysue/r0capture] 怎么连接模拟器 (#26)





  
雷电模拟器的最新版本 Android 7.1.2系统我试验过了，是可以支持使用的！
  
你好，请问如何操作呢？有教程吗？
