### ISSUE TITLE
肉丝姐，报错了自动退出。。。。

### ISSUE THREAD

**Issue by zzzgoda** [r0ysue/r0capture#27]
报错如下：
{'columnNumber': 1,
 'description': 'Error: Implementation for socketRead0 expected return value '
                'compatible with int',
 'fileName': 'frida/node_modules/frida-java-bridge/lib/class-factory.js',
 'lineNumber': 614,
 'stack': 'Error: Implementation for socketRead0 expected return value '
          'compatible with int\n'
          '    at ne '
          '(frida/node_modules/frida-java-bridge/lib/class-factory.js:614)\n'
          '    at <anonymous> '
          '(frida/node_modules/frida-java-bridge/lib/class-factory.js:592)',
 'type': 'error'}
安卓7.1  frida版本 14.2.2和12.8.20都试过，抓的过程中报错如上，试过手淘，美团，拼多多。。。。

**Comment by r0ysue** [comment]
别用模拟器。

**Comment by r0ysue** [comment]
并且 git pull 升级一下。这个bug已经修过了。
