### ISSUE TITLE
Spawn 模式下抓包APP运行慢甚至出现无响应

### ISSUE THREAD

**Issue by ln90s** [r0ysue/r0capture#29]
你好, 环境是真机AOSP 8.1.0系统 , 能够抓包 , 但是运行几个APP均出现页面加载过慢以及卡住甚至出现APP无响应的提示,

请问是在代码哪个地方可能存在这样耗时

或耗费资源过大的地方, 我尝试自己修改一下 , 谢谢!

![image](https://user-images.githubusercontent.com/46208431/103393859-f9366500-4b5f-11eb-8924-85f7e61af25f.png)

**Comment by r0ysue** [comment]
我这边没有出现这样的状况。您可以使用像pixel123这些较快的手机来进行测试。
