### ISSUE TITLE
是否能抓到那些绕过了代理的包？

### ISSUE THREAD

**Issue by nieweiming** [r0ysue/r0capture#32]
是否能抓到那些绕过了代理的包。
程序和正常的charles等抓包工具的原理（中间人攻击）是一样的吗？

示例：mei团外卖app, 获取商超门店信息；
由于有代理检测，所以正常charles是抓不到包的。使用全局代理软件：drony后，是可以抓到包的（也是走http协议）。

1、是否能支持需要全局代理的抓包。
2、全局代理后，app应用能“感知”到使用了代理，这使得响应数据可能异常，是否能避开“感知”，无感知抓包。

**Comment by r0ysue** [comment]
可以。

**Comment by nieweiming** [comment]
从我的实践来看，好像是不行的。
