### ISSUE TITLE
请教下这是什么错误

### ISSUE THREAD

**Issue by renwfy** [r0ysue/r0capture#34]
{'columnNumber': 1,
 'description': "Error: java.lang.ClassNotFoundException: Didn't find class "
                '"java.net.SocketOutputStream" on path: DexPathList[[zip file '
                '"/data/app/com.ysw.app-1/base.apk"],nativeLibraryDirectories=[/data/app/com.ysw.app-1/lib/arm, '
                '/data/app/com.ysw.app-1/base.apk!/lib/armeabi-v7a, '
                '/vendor/lib, /system/lib]]',
 'fileName': 'frida/node_modules/frida-java-bridge/lib/env.js',
 'lineNumber': 126,
 'stack': "Error: java.lang.ClassNotFoundException: Didn't find class "
          '"java.net.SocketOutputStream" on path: DexPathList[[zip file '
          '"/data/app/com.ysw.app-1/base.apk"],nativeLibraryDirectories=[/data/app/com.ysw.app-1/lib/arm, '
          '/data/app/com.ysw.app-1/base.apk!/lib/armeabi-v7a, /vendor/lib, '
          '/system/lib]]\n'
          '    at frida/node_modules/frida-java-bridge/lib/env.js:126\n'
          '    at '
          'frida/node_modules/frida-java-bridge/lib/class-factory.js:459\n'
          '    at '
          'frida/node_modules/frida-java-bridge/lib/class-factory.js:840\n'
          '    at '
          'frida/node_modules/frida-java-bridge/lib/class-factory.js:128\n'
          '    at '
          'frida/node_modules/frida-java-bridge/lib/class-factory.js:83\n'
          '    at /script1.js:193\n'
          '    at frida/node_modules/frida-java-bridge/lib/vm.js:11\n'
          '    at frida/node_modules/frida-java-bridge/index.js:446\n'
          '    at frida/node_modules/frida-java-bridge/index.js:395',
 'type': 'error'}
Terminated: 15

**Comment by renwfy** [comment]
flutter框架下的app

**Comment by owen800q** [comment]
@renwfy 
Flutter App無解，這個不支持

**Comment by owen800q** [comment]
Flutter 的請求框架，沒有用到Java 下的Socket

**Comment by r0ysue** [comment]
Flutter 的請求框架，沒有用到Java 下的Socket
