### ISSUE TITLE
抓包的时候出现好多异常

### ISSUE THREAD

**Issue by NoOne-hub** [r0ysue/r0capture#36]
工具: frida 14.2.3
手机: nexus 5x 
apk: didi
老版本没异常，但是并抓不到didi的什么包
新版本一堆异常还没查看包
![image](https://user-images.githubusercontent.com/43596476/104678615-c9be5580-5726-11eb-9640-3f808b98d5d5.png)
![image](https://user-images.githubusercontent.com/43596476/104678629-d0e56380-5726-11eb-8799-fa40ff7e0f70.png)

**Comment by r0ysue** [comment]
这是新增加的“App收发包函数定位功能”，可以定位到哪些函数在收发包。
