### ISSUE TITLE
5.0盒子报错，找不到类

### ISSUE THREAD

**Issue by duhuanbiao** [r0ysue/r0capture#42]
columnNumber': 1,
 'description': "Error: java.lang.ClassNotFoundException: Didn't find class "
                '"java.net.SocketOutputStream" on path: DexPathList[[zip file '...

**Comment by r0ysue** [comment]
白纸黑字写的7、8、9、10 .

**Comment by duhuanbiao** [comment]
不好意思，没注意看，报错后，直接退出了。
我用frida_ssl_logger可以抓包，但是保存的请求如果是gzip压缩的，dump出来校验和失败，有尝试过么
