### ISSUE TITLE
dump客户端证书 hook java.security.KeyStore$PrivateKeyEntry.init 构造函数会不会更好一点

### ISSUE THREAD

**Issue by daisixuan** [r0ysue/r0capture#43]
直接dump传入私钥和证书链 可以减少重复的证书保存.

![image](https://user-images.githubusercontent.com/42495803/105622324-9f1d7c80-5e4b-11eb-8acc-09ec29fc3335.png)
这里名字不统一 有bug

**Comment by r0ysue** [comment]
dump客户端证书 hook java.security.KeyStore$PrivateKeyEntry.init 构造函数会不会更好一点  →  do it before ask 
这里名字不统一 有bug → 我只是怕漏掉，你用任意一个文件即可

**Comment by daisixuan** [comment]
我试了soul的 dump只出来一份可以用.
![image](https://user-images.githubusercontent.com/42495803/105622395-5b774280-5e4c-11eb-91f9-5389b4fc82b0.png)
如果用getPrivateKey和 getCertificateChain 这个方法必须 要java.security.KeyStore$PrivateKeyEntry 这个对象有这个域吧,所以hook构造函数和这个get 拿到的是同一个私钥和证书链.

![image](https://user-images.githubusercontent.com/42495803/105622438-bf017000-5e4c-11eb-89cb-8fed11b9a275.png)
也可以从内存中choose一份出来保存
![Uploading image.png…]()

**Comment by daisixuan** [comment]
![image](https://user-images.githubusercontent.com/42495803/105622535-51a20f00-5e4d-11eb-9898-5ede47e026a2.png)
