### ISSUE TITLE
"Error: java.lang.ClassNotFoundException: Didn't find class "

### ISSUE THREAD

**Issue by zrk1993** [r0ysue/r0capture#45]
你好 我在使用该脚本时遇到错误了
![image](https://user-images.githubusercontent.com/12870303/105971299-52dd7100-60c5-11eb-8bb4-1058b0ecb9f5.png)
能知道这是怎么回事吗 感谢~

**Comment by amobaishi** [comment]
遇到同样的问题

**Comment by owen800q** [comment]
哪個app

**Comment by canrom7** [comment]
同样的问题， android 6.0  安居客

**Comment by r0ysue** [comment]
白纸黑字写着安卓7、8、9、10 
另外别用模拟器
