### ISSUE TITLE
抓包出错

### ISSUE THREAD

**Issue by amobaishi** [r0ysue/r0capture#47]
![image](https://user-images.githubusercontent.com/39741298/106360260-749f5800-6352-11eb-8389-67a88b18b751.png)

**Comment by r0ysue** [comment]
这是调用栈回溯的功能，是功能，用来定位收发包函数。
不是报错。
Please read the README.md first 。

**Comment by amobaishi** [comment]
明白了  但是后面的包都抓不到了  所以以为是错误
