### ISSUE TITLE
TypeError: not a function

### ISSUE THREAD

**Issue by tmxd09887** [r0ysue/r0capture#53]
r0capture最新版
frida 14.2.3

{'columnNumber': 1,
 'description': 'TypeError: not a function',
 'fileName': '/script1.js',
 'lineNumber': 353,
 'stack': 'TypeError: not a function\n'
          '    at <anonymous> (/script1.js:353)\n'
          '    at apply (native)\n'
          '    at ne '
          '(frida/node_modules/frida-java-bridge/lib/class-factory.js:613)\n'
          '    at <anonymous> '
          '(frida/node_modules/frida-java-bridge/lib/class-factory.js:592)',
 'type': 'error'}

**Comment by r0ysue** [comment]
你这是安卓几？

**Comment by tmxd09887** [comment]
安卓 8.0

**Comment by r0ysue** [comment]
woc 。。。没在8.0上测过
要不你先用8.1？？或者先用上一个版本

**Comment by tmxd09887** [comment]
上一版本哪里下载？

**Comment by r0ysue** [comment]
git clone https://github.com/r0ysue/r0capture.git -b d87d8823431f12edb00601a91ef2acf8b8965831
