### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by safe6Sec** [r0ysue/r0capture#56]
`{'columnNumber': 1,
 'description': "Error: java.lang.ClassNotFoundException: Didn't find class "
                '"java.net.SocketOutputStream" on path: DexPathList[[zip file '
                '"/data/app/com.a9bhuv.z35kb.android-1/base.apk"],nativeLibraryDirectories=[/data/app/com.a9bhuv.z35kb.android-1/lib/arm64, '
                '/data/app/com.a9bhuv.z35kb.android-1/base.apk!/lib/arm64-v8a, '
                '/vendor/lib64, /system/lib64]]',
 'fileName': 'frida/node_modules/frida-java-bridge/lib/env.js',
 'lineNumber': 124,
 'stack': "Error: java.lang.ClassNotFoundException: Didn't find class "
          '"java.net.SocketOutputStream" on path: DexPathList[[zip file '
          '"/data/app/com.a9bhuv.z35kb.android-1/base.apk"],nativeLibraryDirectories=[/data/app/com.a9bhuv.z35kb.android-1/lib/arm64, '
          '/data/app/com.a9bhuv.z35kb.android-1/base.apk!/lib/arm64-v8a, '
          '/vendor/lib64, /system/lib64]]\n'
          '    at <anonymous> '
`

**Comment by r0ysue** [comment]
阅读README
安卓78910且不要用模拟器
