### ISSUE TITLE
写了那么多无视限制之类的话，结果需要root

### ISSUE THREAD

**Issue by weizaishouex2010** [r0ysue/r0capture#57]

**Comment by owen800q** [comment]
root 都不會，你還搞這個?

**Comment by r0ysue** [comment]
root 都不會，你還搞這個?

**Comment by daisixuan** [comment]
你说这话的底层逻辑是什么？顶层设计在哪？最终交付价值是什么？过程的抓手在哪里？如何保证结果的闭环？你比别人的亮点在哪里？优势在哪里？你的思考和沉淀在哪里？你有形成自己的方法论吗？你这话换别人来发是否会不一样？

**Comment by lushann** [comment]
你发这些有什么目的？谁指使你的？你的动机是什么？

**Comment by Fazx** [comment]
你什么星座？你什么学历？问你了吗

**Comment by yeyuchen198** [comment]
确实，想玩深一点没root不行啊，有root之后用小黄鸟抓包就行了

**Comment by tammypi** [comment]
我这边也是，试了一通，结果需要root；有root权限，直接把证书配为系统证书不是更省事...
