### ISSUE TITLE
frida下钩子找不到java.net.SocketInputStream

### ISSUE THREAD

**Issue by pyAppman** [r0ysue/r0capture#58]
java.lang.ClassNotFoundException: Didn't find class \"java.net.SocketInputStream\" on path: DexPathList

**Comment by pyAppman** [comment]
下面是js代码：
function hookInputStream() {
    Java.use('java.net.Socket')['connect'].overload('java.net.SocketAddress').implementation = function(sock_addr) {
        console.log("connect:----------:"+sock_addr)
        var ret_val = this.connect(sock_addr)
        return ret_val
    }
    Java.use("java.net.SocketInputStream").socketRead0.overload('java.io.FileDescriptor', '[B', 'int', 'int', 'int').implementation = function (fd, bytesArray, offset, byteCount, timeout) {
      var result = this.socketRead0(fd, bytesArray, offset, byteCount, timeout);
      var message = {};
      message["function"] = "_recv";
      message["src_addr"] = ntohl(ipToNumber((this.socket.value.getRemoteSocketAddress().toString())));
      message["dst_addr"] = ntohl(ipToNumber((this.socket.value.getLocalAddress().toString())));
      if (result > 0) {
        var ptr = Memory.alloc(result);
        for (var i = 0; i < result; ++i)
          Memory.writeS8(ptr.add(i), bytesArray[offset + i]);
        send(message, Memory.readByteArray(ptr, result))
      }
      return result;
    }
}
Java.perform(hookInputStream);

**Comment by pyAppman** [comment]
一下是我js代码：
`function hookInputStream() {
    Java.use('java.net.Socket')['connect'].overload('java.net.SocketAddress').implementation = function(sock_addr) {
        console.log("connect:----------:"+sock_addr)
        var ret_val = this.connect(sock_addr)
        return ret_val
    }
    Java.use("java.net.SocketInputStream").socketRead0.overload('java.io.FileDescriptor', '[B', 'int', 'int', 'int').implementation = function (fd, bytesArray, offset, byteCount, timeout) {
      var result = this.socketRead0(fd, bytesArray, offset, byteCount, timeout);
      var message = {};
      message["function"] = "_recv";
      message["src_addr"] = ntohl(ipToNumber((this.socket.value.getRemoteSocketAddress().toString())));
      message["dst_addr"] = ntohl(ipToNumber((this.socket.value.getLocalAddress().toString())));
      if (result > 0) {
        var ptr = Memory.alloc(result);
        for (var i = 0; i < result; ++i)
          Memory.writeS8(ptr.add(i), bytesArray[offset + i]);
        send(message, Memory.readByteArray(ptr, result))
      }
      return result;
    }
}
Java.perform(hookInputStream);`

**Comment by pyAppman** [comment]
完整错误如下：
{"type": "error", "description": "Error: java.lang.ClassNotFoundException: Didn't find class \"java.net.SocketInputStream\" on path: DexPathList[[zip file \"/data/app/com.hunantv.imgo.activity-1/base.apk\"],nativeLibraryDirectories=[/data/app/com.hunantv.imgo.activity-1/lib/arm, /data/app/com.hunantv.imgo.activity-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]", "stack": "Error: java.lang.ClassNotFoundException: Didn't find class \"java.net.SocketInputStream\" on path: DexPathList[[zip file \"/data/app/com.hunantv.imgo.activity-1/base.apk\"],nativeLibraryDirectories=[/data/app/com.hunantv.imgo.activity-1/lib/arm, /data/app/com.hunantv.imgo.activity-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]\n    at <anonymous> (frida/node_modules/frida-java-bridge/lib/env.js:124)\n    at <anonymous> (frida/node_modules/frida-java-bridge/lib/class-factory.js:443)\n    at value (frida/node_modules/frida-java-bridge/lib/class-factory.js:812)\n    at _make (frida/node_modules/frida-java-bridge/lib/class-factory.js:112)\n    at use (frida/node_modules/frida-java-bridge/lib/class-factory.js:63)\n    at use (frida/node_modules/frida-java-bridge/index.js:246)\n    at hookInputStream (/script1.js:187)\n    at <anonymous> (frida/node_modules/frida-java-bridge/lib/vm.js:16)\n    at _performPendingVmOps (frida/node_modules/frida-java-bridge/index.js:238)\n    at <anonymous> (frida/node_modules/frida-java-bridge/index.js:213)\n    at <anonymous> (frida/node_modules/frida-java-bridge/lib/vm.js:16)\n    at _performPendingVmOpsWhenReady (frida/node_modules/frida-java-bridge/index.js:232)\n    at perform (frida/node_modules/frida-java-bridge/index.js:192)\n    at <eval> (/script1.js:218)", "fileName": "frida/node_modules/frida-java-bridge/lib/env.js", "lineNumber": 124, "columnNumber": 1}

**Comment by r0ysue** [comment]
读一下README
别用模拟器。
安卓7 8 9 10 11
