### ISSUE TITLE
报错：More than one match found for *libssl*!SSL_read

### ISSUE THREAD

**Issue by soh0ro0t** [r0ysue/r0capture#59]
环境：
测试手机：andorid 11
frida环境：windows10

运行指令：
python r0capture.py -U -p any.pcap  -ssl "*libssl.so*" com.sina.weibo

错误提示：
attach
{'description': 'More than one match found for *libssl*!SSL_read: '
                '/system/lib/libssl.so!SSL_read@0xdb06223d, '
                '/apex/com.android.conscrypt/lib/libssl.so!SSL_read@0xd95e123d',
 'type': 'error'}

然后更改了ssl参数为“-ssl /system/lib/libssl.so”依然同样错，说明该参数设置没有生效，是怎么回事？

**Comment by r0ysue** [comment]
bug
