### ISSUE TITLE
无报错，抓不到包

### ISSUE THREAD

**Issue by ruthless2012** [r0ysue/r0capture#62]
环境：
Android 8.1.0，已用magisk root
frida 14.2.18
python 3.9.5

使用attach模式保存为pcap文件，wireshark打开是空的
没有报错
![image](https://user-images.githubusercontent.com/44649077/122008597-d507d100-cdeb-11eb-8937-9b6056da4c33.png)
![image](https://user-images.githubusercontent.com/44649077/122008641-de913900-cdeb-11eb-9307-de3aaf5e5c29.png)

**Comment by r0ysue** [comment]
1. spawn模式试试看
2. 读下README.md中的限制条件
