### ISSUE TITLE
关于加载了多个libssl.so库导致报错的问题

### ISSUE THREAD

**Issue by zdccc** [r0ysue/r0capture#67]
![image](https://user-images.githubusercontent.com/18638203/124214745-4b633d80-db25-11eb-8142-0b5e0a1cd6b0.png)
这个问题有计划解决么，我看当前 -ssl 参数好像没有效果，只能把代码里面这个报错去掉，手动尝试一下使用的是哪个so库

**Comment by r0ysue** [comment]
自定义的ssl，得分析so库，指定了也是无效的。
