### ISSUE TITLE
More than one match found for *libssl*!SSL_read

### ISSUE THREAD

**Issue by Miscf** [r0ysue/r0capture#76]
当我用这个框架想去hook淘宝的时候，他抱错了，其中的内容是

> {'description': 'More than one match found for *libssl*!SSL_read: '
                '/apex/com.android.conscrypt/lib/libssl.so!SSL_read@0xd1fe38a5, '
                '/data/app/com.taobao.taobao-XVnyJTItLkVOsWMi8aqRLw==/lib/arm/libssl.1.0.2.so!SSL_read@0x998ae658',
 'type': 'error'}

似乎是因为淘宝使用了多个libssl.so
所以现在我需要如何通过改r0capture源代码解决这个问提呢？

**Comment by yinzehaonb** [comment]
遇到了同样的问题
