### ISSUE TITLE
frida.ServerNotRunningError: unable to connect to remote frida-server: closed

### ISSUE THREAD

**Issue by ftyszyx** [r0ysue/r0capture#8]
frida.ServerNotRunningError: unable to connect to remote frida-server: closed

**Comment by r0ysue** [comment]
按照这个教程配置好环境：
https://github.com/r0ysue/AndroidSecurityStudy/blob/master/FRIDA/A01/README.md

**Comment by nieweiming** [comment]
脚本执行之前，输入：
adb forward tcp:27043 tcp:27043
adb forward tcp:27042 tcp:27042

**Comment by 1542838777** [comment]
> 脚本执行之前，输入： adb forward tcp:27043 tcp:27043 adb forward tcp:27042 tcp:27042

thanks ，  it is useful
