### ISSUE TITLE
More than one match found for *libssl*!SSL_read

### ISSUE THREAD

**Issue by dkfjsdk** [r0ysue/r0capture#80]
{'description': 'More than one match found for *libssl*!SSL_read: '
                '/system/lib/libssl.so!SSL_read@0xda2e78a5, '
                '/apex/com.android.conscrypt/lib/libssl.so!SSL_read@0xd2fe281d',
 'type': 'error'}

**Comment by r0ysue** [comment]
You can fix it by amend source code
