### ISSUE TITLE
app存在几个同名进程会报错，建议添加按进程号抓包

### ISSUE THREAD

**Issue by chaserw** [r0ysue/r0capture#86]
如题，报错：
`frida.ProcessNotFoundError: ambiguous name; it matches: com.xxx.xxx (pid: 19680), com.xxx.xxx (pid: 19828), com.xxx.xxx (pid: 19839), com.xxx.xxx (pid: 19841)`
查看进程，确实存在一些同名进程
`u0_a151      18874 18639 0 16:52:00 ?     00:00:00 com.xxx.xxx`
`u0_a151      18918 18639 12 16:52:01 ?    00:02:11 com.xxx.xxx`
`u0_a151      18920 18918 0 16:52:01 ?     00:00:00 com.xxx.xxx`

**Comment by r0ysue** [comment]
同名进程可以使用pid来指定具体的进程
