### ISSUE TITLE
打印的日志去哪了？

### ISSUE THREAD

**Issue by shejishi** [r0ysue/r0capture#88]
Press Ctrl+C to stop logging.

**Comment by shejishi** [comment]
本人小白，安装好frida之后，也获取了root，调用`python3 r0capture.py -U -f cn.soulapp.android -v`，出现`Press Ctrl+C to stop logging.`，然后点击app之后也没看到日志出现，是保存到其他地方了吗？

**Comment by shejishi** [comment]
使用`attatch`模式，出现

**Comment by r0ysue** [comment]
这是frida15的bug，可以使用frida12+安卓7，或者frida14+安卓10 ，这样的搭配组合。
