### ISSUE TITLE
frida15.1.27   android8.0

### ISSUE THREAD

**Issue by PythonMengQH** [r0ysue/r0capture#94]
{'type': 'error', 'description': 'TypeError: not a function', 'stack': 'TypeError: not a function\n    at _enumerateClassLoadersArt (frida/node_modules/frida-java-bridge/index.js:154)\n    at enumerateClassLoaders (frida/node_modules/frida-java-bridge/index.js:83)\n    at <anonymous> (/script1.js:27)\n    at <anonymous> (frida/node_modules/frida-java-bridge/lib/vm.js:12)\n    at _performPendingVmOps (frida/node_modules/frida-java-bridge/index.js:250)\n    at <anonymous> (frida/node_modules/frida-java-bridge/index.js:225)\n    at <anonymous> (frida/node_modules/frida-java-bridge/lib/vm.js:12)\n    at _performPendingVmOpsWhenReady (frida/node_modules/frida-java-bridge/index.js:244)\n    at perform (frida/node_modules/frida-java-bridge/index.js:204)\n    at <eval> (/script1.js:28)', 'fileName': 'frida/node_modules/frida-java-bridge/index.js', 'lineNumber': 154, 'columnNumber': 1}

**Comment by r0ysue** [comment]
安卓8的话推荐frida 12.8.0版本
